/*=========================================================================

   Program:   ParaQ
   Module:    $RCSfile: pqSamplingGridPanel.h,v $

   Copyright (c) 2005,2006 Sandia Corporation, Kitware Inc.
   All rights reserved.

   ParaQ is a free software; you can redistribute it and/or modify it
   under the terms of the ParaQ license version 1.1. 

   See License_v1.1.txt for the full ParaQ license.
   A copy of this license can be obtained by contacting
   Kitware Inc.
   28 Corporate Drive
   Clifton Park, NY 12065
   USA

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHORS OR
CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

=========================================================================*/

#ifndef _pqSamplingGridPanel_h
#define _pqSamplingGridPanel_h

#include "pqAutoGeneratedObjectPanel.h"

class pqServer;
class pqBoxWidget;
class pqImplicitPlaneWidget;

/// Provides a complete Qt UI for working with a 3D box/plane widget

/// BUG: Currently we work directly with the source, when compuing OBB
/// or snap to X/Y/Z axis, this means properties are set directly on
/// the objects and we can't "undo" by pressing reset before accept.

class pqSamplingGridPanel :
  public pqAutoGeneratedObjectPanel
{
  typedef pqAutoGeneratedObjectPanel Superclass;
  
  Q_OBJECT
  
public:
   pqSamplingGridPanel(pqProxy* pxy, QWidget* p);
  ~pqSamplingGridPanel();

  virtual void createWidget(pqServer* server);

  /// We need to generate the correct source settings
  /// (origin, point1, point2, point3) when the widget is accepted.
  virtual void accept();

  /// Do the correct (origin, point1, point2, point3) calculation
  void ComputePlanePoints();

protected:
  int getReferenceInputBounds(double bounds[6]) const;
  /// these are used internally and stored so that the 
  /// pqSamplingGridPanel subclass can use them to
  /// compute plane p1 and p2 points
  double InputBounds[6];
  double SizeFactor;

  pqBoxWidget           *boxWidget;
  pqImplicitPlaneWidget *planeWidget;
  int                    currentMode;

public slots:
  void setView(pqView* pqview);

private slots:
  /// Called to set the widget normal to the camera direction
  void onUseCameraNormal();
  /// called when switching between plane/box mode
  void onWidgetModeChanged(int index);
  /// When a plane parater changes, we must recompute
  void UpdatePlanePoints();

  void onWidgetModified();

private:
  class pqImplementation;
  pqImplementation *Implementation;
};

#endif
